/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca;

import conexao.Conexao;
<<<<<<< HEAD
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.font.TextAttribute;
import java.sql.SQLException;
import java.util.Map;
import javax.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Gabriel Santos
 */
public class LoginAdmin extends javax.swing.JFrame {
    
    Conexao con_cliente;

  
    public LoginAdmin() {
        initComponents();
            con_cliente = new Conexao(); 
            con_cliente.conecta(); 
    
        ImageIcon icone = new ImageIcon("src/img/logoicon.png");
        setIconImage(icone.getImage());
        
=======

/**
 *
 * @author Gabriel
 */
public class LoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Conexao con_cliente;
    
    public LoginAdmin() {
        initComponents();
        
         Conexao con_cliente;
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        Esquerda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
<<<<<<< HEAD
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogar = new javax.swing.JButton();
        Direita = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN DE ADMIN");
        setResizable(false);
=======
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Direita = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN DE ADMIN");
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6

        JPanel1.setBackground(new java.awt.Color(48, 145, 144));
        JPanel1.setForeground(new java.awt.Color(255, 255, 255));
        JPanel1.setName(""); // NOI18N
        JPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        JPanel1.setLayout(null);

        Esquerda.setBackground(new java.awt.Color(255, 255, 255));
        Esquerda.setMinimumSize(new java.awt.Dimension(400, 500));
        Esquerda.setName(""); // NOI18N
        Esquerda.setPreferredSize(new java.awt.Dimension(400, 500));
        Esquerda.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("LOGIN DE ADMIN");
        Esquerda.add(jLabel1);
        jLabel1.setBounds(50, 10, 610, 100);

<<<<<<< HEAD
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        Esquerda.add(txtUsuario);
        txtUsuario.setBounds(30, 150, 340, 30);

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        Esquerda.add(txtSenha);
        txtSenha.setBounds(30, 220, 340, 30);
=======
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        Esquerda.add(jTextField2);
        jTextField2.setBounds(30, 150, 340, 30);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        Esquerda.add(jPasswordField1);
        jPasswordField1.setBounds(30, 220, 340, 30);
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Senha:");
        Esquerda.add(jLabel2);
        jLabel2.setBounds(30, 190, 60, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Email:");
        Esquerda.add(jLabel3);
        jLabel3.setBounds(30, 120, 60, 20);

<<<<<<< HEAD
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("É Usuário? Entre aqui!");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        Esquerda.add(jLabel4);
        jLabel4.setBounds(120, 390, 190, 25);

        btnLogar.setBackground(new java.awt.Color(58, 174, 173));
        btnLogar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogar.setText("Login");
        btnLogar.setName("btnLogar"); // NOI18N
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        Esquerda.add(btnLogar);
        btnLogar.setBounds(150, 290, 110, 30);
=======
        jButton2.setBackground(new java.awt.Color(58, 174, 173));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Entre aqui!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Esquerda.add(jButton2);
        jButton2.setBounds(90, 450, 130, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("É Usuário? ");
        Esquerda.add(jLabel4);
        jLabel4.setBounds(20, 450, 80, 20);

        jButton4.setBackground(new java.awt.Color(58, 174, 173));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Esquerda.add(jButton4);
        jButton4.setBounds(150, 290, 110, 30);
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6

        JPanel1.add(Esquerda);
        Esquerda.setBounds(0, 0, 400, 500);

        Direita.setBackground(new java.awt.Color(48, 145, 144));
        Direita.setMinimumSize(new java.awt.Dimension(400, 500));

<<<<<<< HEAD
=======
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6
        jLabel8.setText("© 2024  BiblioOH®. Todos os direitos reservados");

        javax.swing.GroupLayout DireitaLayout = new javax.swing.GroupLayout(Direita);
        Direita.setLayout(DireitaLayout);
        DireitaLayout.setHorizontalGroup(
            DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(DireitaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addContainerGap(1358, Short.MAX_VALUE))
=======
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DireitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(72, 72, 72))
            .addGroup(DireitaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addContainerGap(90, Short.MAX_VALUE))
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6
        );
        DireitaLayout.setVerticalGroup(
            DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DireitaLayout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(461, 461, 461)
=======
                .addGap(39, 39, 39)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6
                .addComponent(jLabel8)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        JPanel1.add(Direita);
<<<<<<< HEAD
        Direita.setBounds(420, 0, 1668, 500);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.png"))); // NOI18N
=======
        Direita.setBounds(400, 0, 400, 500);
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
=======
            .addGap(0, 800, Short.MAX_VALUE)
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
=======
            .addGap(0, 500, Short.MAX_VALUE)
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed

                          

try {
    // Monta a query manualmente, concatenando o email e a senha diretamente
    String pesquisa = "SELECT f.* FROM funcionario f "
                    + "INNER JOIN conta_administrador c ON f.Id_Funcionario = c.Id_Funcionario "
                    + "WHERE f.Email = '" + txtUsuario.getText() + "' "
                    + "AND c.Senha = '" + new String(txtSenha.getPassword()) + "'";

    // Executa a query
    con_cliente.executaSQL(pesquisa);

    // Verifica se houve resultado
    if (con_cliente.resultset.first()) {
        
       
        // Acesso permitido: abre a tela do administrador
        PageInicialAdmin mostra = new PageInicialAdmin();
        mostra.setVisible(true);
        dispose(); // Fecha a janela de login
    } else {
        // Caso não encontre o usuário ou a senha estejam errados
        JOptionPane.showMessageDialog(null, "E-mail ou senha incorretos", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
    }
} catch (SQLException erroSql) {
    // Exibe mensagem de erro caso haja exceção de SQL
    JOptionPane.showMessageDialog(null, "Erro ao acessar os dados!\n" + erroSql, "Mensagem do Programa", JOptionPane.ERROR_MESSAGE);
}


     

    }//GEN-LAST:event_btnLogarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        Font font = jLabel4.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        jLabel4.setFont(font.deriveFont(attributes));
        jLabel4.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        jLabel4.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
=======
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
<<<<<<< HEAD
    }//GEN-LAST:event_jLabel4MouseClicked
=======
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Direita;
    private javax.swing.JPanel Esquerda;
    private javax.swing.JPanel JPanel1;
<<<<<<< HEAD
    private javax.swing.JButton btnLogar;
=======
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
=======
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
>>>>>>> afbbb357595d021912e2ce7eca2c6bfc2d6aa8c6
    // End of variables declaration//GEN-END:variables
}
