package biblioteca;

import conexao.Conexao;
import java.awt.Color;
import javaswingdev.drawer.Drawer; 
import javaswingdev.drawer.DrawerController; 
import javaswingdev.drawer.DrawerItem; 
import javax.swing.ImageIcon;
import javax.swing.JLabel;



/**
 *
 * @author Admin
 */
public class PageInicialUser extends javax.swing.JFrame {
         Conexao con_cliente;
    
   private DrawerController drawer;
    public PageInicialUser() {
        

         
        initComponents();
        drawer=Drawer.newDrawer(this)
                .header(new Header())
                .background(new Color(255,255,255))
                .backgroundTransparent(0.0f)
                .drawerBackground(new Color(48,145,144))
                .drawerWidth(300)
                .addChild(new DrawerItem("Página Inicial").icon(new ImageIcon(getClass().getResource("/img/homeheader.png"))).build())
                .addChild(new DrawerItem("Meu Perfil").icon(new ImageIcon(getClass().getResource("/img/perfilheader.png"))).build())
                .addChild(new DrawerItem("Livros").icon(new ImageIcon(getClass().getResource("/img/livroheader.png"))).build())
                .addChild(new DrawerItem("Meus Empréstimos").icon(new ImageIcon(getClass().getResource("/img/emprestimoheader.png"))).build())
                .addChild(new DrawerItem("Setores da Blibioteca").icon(new ImageIcon(getClass().getResource("/img/setorheader.png"))).build())
                .addChild(new DrawerItem("Sobre Nós").icon(new ImageIcon(getClass().getResource("/img/sobrenosheader.png"))).build())
               
               
                .addFooter(new DrawerItem("Sair").icon(new ImageIcon(getClass().getResource("/img/sairheader.png"))).build())
 
                .build();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página Inicial");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(48, 145, 144));

        menu.setBackground(new java.awt.Color(48, 145, 144));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuhamburguer.png"))); // NOI18N
        menu.setBorder(null);
        menu.setBorderPainted(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoheader.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(537, 537, 537))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(menu)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 580, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        if(drawer.isShow()){
            drawer.hide();
        
        }else{
            drawer.show();
        }
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 PageInicialUser PageInicialFrame = new PageInicialUser();
                 PageInicialFrame.setVisible(true);
                 PageInicialFrame.pack();
                 PageInicialFrame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton menu;
    // End of variables declaration//GEN-END:variables
}
