package biblioteca;

import conexao.Conexao;
import java.awt.Color;
import javaswingdev.drawer.Drawer; 
import javaswingdev.drawer.DrawerController; 
import javaswingdev.drawer.DrawerItem; 
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;



/**
 *
 * @author Admin
 */
public class SobreNos extends javax.swing.JFrame {

      Conexao con_cliente;
        
   private DrawerController drawer;
    public SobreNos() {
      
       
        
        initComponents();
       drawer=Drawer.newDrawer(this)
                .header(new Header())
                .background(new Color(255,255,255))
                .backgroundTransparent(0.0f)
                .drawerBackground(new Color(48,145,144))
                .drawerWidth(300)
                .closeOnPress(false)
                .addChild(home)
                .addChild(meuperfil)
                .addChild(usuarios)
                .addChild(livro)
                .addChild(funcionario)
                .addChild(adLivro)
                .addChild(emprestimos)
                .addChild(cargos)
                .addChild(periodo)
                .addChild(setores)
                
              
                
                
                .addFooter(sair)
                
                .build();  
        
        
         drawer.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        periodo = new javax.swing.JButton();
        usuarios = new javax.swing.JButton();
        livro = new javax.swing.JButton();
        emprestimos2 = new javax.swing.JButton();
        funcionario = new javax.swing.JButton();
        sobrenos = new javax.swing.JButton();
        cargos = new javax.swing.JButton();
        home = new javax.swing.JButton();
        meuperfil = new javax.swing.JButton();
        emprestimos = new javax.swing.JButton();
        adLivro = new javax.swing.JButton();
        setores = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSobre = new javax.swing.JLabel();
        imageAvatar3 = new biblioteca.ImageAvatar();
        imageAvatar4 = new biblioteca.ImageAvatar();
        imageAvatar7 = new biblioteca.ImageAvatar();
        imageAvatar8 = new biblioteca.ImageAvatar();
        imageAvatar9 = new biblioteca.ImageAvatar();
        imageAvatar10 = new biblioteca.ImageAvatar();
        imageAvatar11 = new biblioteca.ImageAvatar();
        imageAvatar12 = new biblioteca.ImageAvatar();
        imageAvatar13 = new biblioteca.ImageAvatar();
        imageAvatar14 = new biblioteca.ImageAvatar();
        lblSobre1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSobre2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSobre3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        periodo.setBackground(new java.awt.Color(48, 145, 144));
        periodo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        periodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/periodoheader.png"))); // NOI18N
        periodo.setText("Período");
        periodo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodoActionPerformed(evt);
            }
        });

        usuarios.setBackground(new java.awt.Color(48, 145, 144));
        usuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userheader.png"))); // NOI18N
        usuarios.setText("Usuarios");
        usuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });

        livro.setBackground(new java.awt.Color(48, 145, 144));
        livro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adlivroheader.png"))); // NOI18N
        livro.setText("Livro");
        livro.setAlignmentY(2.0F);
        livro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        livro.setName("livro"); // NOI18N
        livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livroActionPerformed(evt);
            }
        });

        emprestimos2.setBackground(new java.awt.Color(48, 145, 144));
        emprestimos2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emprestimos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emprestimoheader.png"))); // NOI18N
        emprestimos2.setText("Empréstimos");
        emprestimos2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emprestimos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimos2ActionPerformed(evt);
            }
        });

        funcionario.setBackground(new java.awt.Color(48, 145, 144));
        funcionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcheader.png"))); // NOI18N
        funcionario.setText("Funcionário");
        funcionario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });

        sobrenos.setBackground(new java.awt.Color(48, 145, 144));
        sobrenos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sobrenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sobrenosheader.png"))); // NOI18N
        sobrenos.setText("Sobre Nós");
        sobrenos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sobrenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenosActionPerformed(evt);
            }
        });

        cargos.setBackground(new java.awt.Color(48, 145, 144));
        cargos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cargoheader.png"))); // NOI18N
        cargos.setText("Cargos");
        cargos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargosActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(48, 145, 144));
        home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homeheader.png"))); // NOI18N
        home.setText("Página Inicial");
        home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        meuperfil.setBackground(new java.awt.Color(48, 145, 144));
        meuperfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        meuperfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfilheader.png"))); // NOI18N
        meuperfil.setText("Meu Perfil");
        meuperfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        meuperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meuperfilActionPerformed(evt);
            }
        });

        emprestimos.setBackground(new java.awt.Color(48, 145, 144));
        emprestimos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emprestimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emprestimoheader.png"))); // NOI18N
        emprestimos.setText("Empréstimos");
        emprestimos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimosActionPerformed(evt);
            }
        });

        adLivro.setBackground(new java.awt.Color(48, 145, 144));
        adLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adlivroheader.png"))); // NOI18N
        adLivro.setText("Administrar Livro");
        adLivro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adLivroActionPerformed(evt);
            }
        });

        setores.setBackground(new java.awt.Color(48, 145, 144));
        setores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        setores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setorheader.png"))); // NOI18N
        setores.setText("Setores");
        setores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setoresActionPerformed(evt);
            }
        });

        sair.setBackground(new java.awt.Color(48, 145, 144));
        sair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sairheader.png"))); // NOI18N
        sair.setText("Sair");
        sair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página Inicial");
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(48, 145, 144));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoheader.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(444, 444, 444))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        lblSobre.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSobre.setForeground(new java.awt.Color(0, 102, 102));
        lblSobre.setText("Gabriel Santos");

        imageAvatar3.setBorderSize(3);
        imageAvatar3.setBorderSpace(2);
        imageAvatar3.setImage(new javax.swing.ImageIcon(getClass().getResource("/img/foto.jpg"))); // NOI18N
        imageAvatar3.add(imageAvatar4);
        imageAvatar4.setBounds(0, 0, 0, 0);

        imageAvatar7.setBorderSize(3);
        imageAvatar7.setBorderSpace(2);
        imageAvatar7.setImage(new javax.swing.ImageIcon(getClass().getResource("/img/fotoBielOliveira.jpg"))); // NOI18N
        imageAvatar7.add(imageAvatar8);
        imageAvatar8.setBounds(0, 0, 0, 0);

        imageAvatar9.add(imageAvatar10);
        imageAvatar10.setBounds(0, 0, 0, 0);

        imageAvatar7.add(imageAvatar9);
        imageAvatar9.setBounds(0, 0, 0, 0);

        imageAvatar11.setBorderSize(3);
        imageAvatar11.setBorderSpace(2);
        imageAvatar11.setDoubleBuffered(true);
        imageAvatar11.setImage(new javax.swing.ImageIcon(getClass().getResource("/img/fotoGui.jpg"))); // NOI18N
        imageAvatar11.add(imageAvatar12);
        imageAvatar12.setBounds(0, 0, 0, 0);

        imageAvatar13.add(imageAvatar14);
        imageAvatar14.setBounds(0, 0, 0, 0);

        imageAvatar11.add(imageAvatar13);
        imageAvatar13.setBounds(0, 0, 0, 0);

        lblSobre1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSobre1.setForeground(new java.awt.Color(0, 102, 102));
        lblSobre1.setText("Desenvolvido por:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 118, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("gabriel.ps.gs.74@gmail.com");

        lblSobre2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSobre2.setForeground(new java.awt.Color(0, 102, 102));
        lblSobre2.setText("Guilherme Santos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 118, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("gabriel.ps.gs.74@gmail.com");

        lblSobre3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSobre3.setForeground(new java.awt.Color(0, 102, 102));
        lblSobre3.setText("Gabriel Oliveira");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 118, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("gabriel.ogfs@gmail.com");

        jLabel8.setText("© 2024  BiblioOH®. Todos os direitos reservados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imageAvatar11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblSobre2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblSobre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imageAvatar7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblSobre3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(448, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSobre1)
                .addGap(302, 302, 302))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblSobre1)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAvatar11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSobre2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(imageAvatar7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblSobre3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodoActionPerformed

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariosActionPerformed

    private void livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livroActionPerformed

    }//GEN-LAST:event_livroActionPerformed

    private void emprestimos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emprestimos2ActionPerformed

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed

    }//GEN-LAST:event_funcionarioActionPerformed

    private void sobrenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenosActionPerformed

    private void cargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargosActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void meuperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meuperfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meuperfilActionPerformed

    private void emprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emprestimosActionPerformed

    private void adLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adLivroActionPerformed

    private void setoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setoresActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        int opcao;
        opcao = JOptionPane.showConfirmDialog(null, "Deseja mesmo fechar a janela", "Sair", JOptionPane.YES_NO_OPTION);
        if(opcao == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adLivro;
    private javax.swing.JButton cargos;
    private javax.swing.JButton emprestimos;
    private javax.swing.JButton emprestimos2;
    private javax.swing.JButton funcionario;
    private javax.swing.JButton home;
    private biblioteca.ImageAvatar imageAvatar10;
    private biblioteca.ImageAvatar imageAvatar11;
    private biblioteca.ImageAvatar imageAvatar12;
    private biblioteca.ImageAvatar imageAvatar13;
    private biblioteca.ImageAvatar imageAvatar14;
    private biblioteca.ImageAvatar imageAvatar3;
    private biblioteca.ImageAvatar imageAvatar4;
    private biblioteca.ImageAvatar imageAvatar7;
    private biblioteca.ImageAvatar imageAvatar8;
    private biblioteca.ImageAvatar imageAvatar9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSobre;
    private javax.swing.JLabel lblSobre1;
    private javax.swing.JLabel lblSobre2;
    private javax.swing.JLabel lblSobre3;
    private javax.swing.JButton livro;
    private javax.swing.JButton meuperfil;
    private javax.swing.JButton periodo;
    private javax.swing.JButton sair;
    private javax.swing.JButton setores;
    private javax.swing.JButton sobrenos;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables
}
